### ISSUE TITLE
Common properties defined in different modules should not use domain or range

### ISSUE THREAD

**Issue by avillar** [ogcincubator/cityrdf#11]
Properties like [`common:class`](https://github.com/ogcincubator/cityrdf/blob/8c2f9bba8cc4256b95a681df84f5f77dbc09d654/citygml-owl/CityOWL/building.ttl#L603) should use domainIncludes/rangeIncludes instead of domain/range, since several domain/range for a single predicate (i.e., when parsing the whole ontology) results in the domain/range being the intersection of the classes.

**Comment by nataschake** [comment]
done in https://github.com/ogcincubator/cityrdf/commit/f16add200c9fa4a36d6fb4e76ae8e4c402611ada
