### ISSUE TITLE
Reserving a namespace for citygml owl/rdf

### ISSUE THREAD

**Issue by nataschake** [ogcincubator/cityrdf#7]
(Vote @rob-metalinkage @avillar @VladimirAlexiev @ar-chad @svilenvarbanov2019 )
We talked about
- [ ] `https://www.opengis.net/ont/citygml/3.0/rdf`
- [ ]  `https://www.opengis.net/ont/citygml/3.0/owl` 
separation (e.g. in light of [alternatives](https://github.com/ogcincubator/cityrdf/issues/6)(RDFS style) and 1.2(OWL style), but we could leave
- [ ] `https://www.opengis.net/ont/citygml/` assuming the only one presentation of CityGML 3.0 will be used broadly.

**Comment by VladimirAlexiev** [comment]
I vote for https://www.opengis.net/ont/citygml/.
IMHO having RDFS vs OWL versions of the ontology will just lead to confusion...

**Comment by nataschake** [comment]
I only think if we can keep the version of CityGML?

**Comment by rob-metalinkage** [comment]
I'd rather have one namespace - not separate versions - but if we have a major semantic incompatibility we need to understand how to handle it.   I'd love to have Ontotext's view on the most sustainable approach to versioning...

**Comment by nataschake** [comment]
I will use https://www.opengis.net/ont/citygml/3.0/building/ and all of the kind.

Initially the namespaces are declared as e.g., [http://www.opengis.net/citygml/building/2.0](http://www.opengis.net/citygml/building/2.0), so the version is in the namespace URI.

**Comment by nataschake** [comment]
Again, we follow "slash-not-hash" way, so all the namespaces that are now like:
<https://www.opengis.net/ont/citygml/3.0/building#> will be 
<https://www.opengis.net/ont/citygml/3.0/building/>

**Comment by VladimirAlexiev** [comment]
@nataschake Using version numbers in ontology term URLs makes them unstable.
People want to use the latest version, so if the version is changed, they need to do database migrations.
This causes pain, eg see in Electrical CIM:
- https://github.com/Sveino/Inst4CIM-KG/issues/70
- https://github.com/Sveino/Inst4CIM-KG/issues/123

We can use `owl:versionIRI, versionInfo` to capture the version. Eg:

```ttl
@prefix citygml: <https://www.opengis.net/ont/citygml/>.

citygml: a owl:Ontology;
  owl:versionIRI <https://www.opengis.net/ont/citygml/3.0.0/>;
  owl:versionInfo "3.0.0"
  ...
```

**Comment by nataschake** [comment]
version info added to CityOWL.ttl
